name: Build Windows Desktop App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
      ELECTRON_BUILDER_DEBUG: "true"
      DEBUG: "electron-builder"
      CI: "true"
      USE_HARD_LINKS: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NSIS
        shell: pwsh
        run: choco install nsis -y

      - name: Install dependencies
        shell: pwsh
        run: npm install

      - name: Upgrade builder tools
        shell: pwsh
        run: npm install --save-dev electron-builder@latest app-builder-bin@latest

      - name: Unblock app-builder.exe
        shell: pwsh
        run: |
          $exe = "node_modules\app-builder-bin\win\x64\app-builder.exe"
          if (Test-Path $exe) { Unblock-File $exe }

      - name: Build installer
        shell: pwsh
        run: npx electron-builder --win --x64 --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WasteRouteProDist
          path: dist/**
