name: Build Windows Desktop App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      # hard-disable auto code-sign & publishing in CI
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"
      ELECTRON_BUILDER_DEBUG: "true"
      DEBUG: "electron-builder"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          echo "Top-level files:"; dir
          echo "--- package.json (preview) ---"
          if exist package.json (type package.json) else (echo "NO package.json at repo root!")

     
